### ISSUE TITLE
no information about token.txt

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [rflechner/SlackTypeProvider#3]
No where in the presentation, nor on the code readme.md do I see any information about what is supposed to be in `token.txt`. Looking at the slack API page, it shows me a client ID and a secret. not anything called a token.

**Comment by ImaginaryDevelopment** [comment]
Ok, I think this would be nice to add somewhere besides to a issue that will be closed. Apparently you have to install your slack app to a specific channel before it will give you a `token`. I had no idea why the page linked in my presentation said I had no apps, after seeing clearly on another page I had an app created.

**Comment by rflechner** [comment]
Hi, 
You can create your bot and get a token here: [https://api.slack.com/bot-users](https://api.slack.com/bot-users)
Then, you have to put token in token.txt.
