### ISSUE TITLE
The type provider 'ProviderImplementation.SlackTypeProvider' reported an error 

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [rflechner/SlackTypeProvider#4]
The type provider 'ProviderImplementation.SlackTypeProvider' reported an error: Object reference not set to an instance of an object

```
// dll seems to be hard coded to require 8.0
#r @"C:\Users\Brandon\AppData\Local\LINQPad\NuGet.FW46\Newtonsoft.Json 8.0.1\Newtonsoft.Json.8.0.1\lib\net45\Newtonsoft.Json.dll"
#r @"C:\Users\Brandon\AppData\Local\LINQPad\NuGet.FW46\SlackTypeProvider\SlackTypeProvider.0.0.7\lib\net40\SlackTypeProvider.dll"

open SlackProvider
[<Literal>]
let path = @"C:\Users\Brandon\AppData\Local\slackApi\token.txt"
// ran the following commented out line to make sure the file exists and has a proper value.
//System.IO.File.ReadAllText(path)

// red underline here on everything to the ride side of `TSlack = `
type TSlack = SlackTypeProvider<token= path>
```

I would like to think, naively, that there is some way in type providers to wrap unhandled exceptions to either log them, or show more information up in the error tooltip.

Either way, I imagine the only way to get you more information is to download the source code, build it, and setup one VS instance to debug another? Or perhaps there's a chance you know where this would be without all that work.

**Comment by rflechner** [comment]
Hi,
I think you are not using a 'Bot user'.
Did you go to https://api.slack.com/bot-users and clicked on 'creating a new bot user' ?
